name: tests and merge PR

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3  # Use the latest stable version of actions/checkout
    - name: Set up JDK 22
      uses: actions/setup-java@v3  # Use the latest version of setup-java
      with:
        java-version: 22
    - name: Cache Maven packages
      uses: actions/cache@v3  # Use the latest stable version of actions/cache
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Run tests with Maven
      run: mvn -B test --file pom.xml

  merge_pr:
    needs: run_tests  # Ensure tests run before attempting merge
    if: github.event.pull_request.draft == false && github.event.pull_request.mergeable == true  # Only merge if PR is not a draft and is mergeable
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3  # Ensure you checkout the repository in this job too
    - name: Automerge the PR
      uses: pascalgn/automerge-action@v0.14.3  # Automerge action version you are using
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_LABELS: "Automerge"  # Optional: Automate merging based on labels
        MERGE_METHOD: "squash"  # Choose the merge method (e.g., squash)
        MERGE_COMMIT_MESSAGE: "Merge PR: ${GITHUB_HEAD_REF}"  # Customize commit message (optional)
