name: Tests and Merge PR

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, labeled, unlabeled] # Trigger on PR events like opening, syncing, labeling

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        java-version: 22
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Run tests with Maven
      run: mvn -B test --file pom.xml

  merge_pr:
    needs: run_tests
    if: >
      github.event.pull_request.draft == false &&
      github.event.pull_request.mergeable == true &&
      contains(github.event.pull_request.labels.*.name, 'Automerge')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Automerge the PR
      uses: pascalgn/automerge-action@v0.14.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MERGE_LABELS: "Automerge"
        MERGE_METHOD: "squash"
        MERGE_COMMIT_MESSAGE: "Merge PR: ${{ github.head_ref }}"
