name: tests and Auto Merge PR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up JDK 22
      uses: actions/setup-java@v1
      with:
        java-version: 22

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Run tests with Maven
      run: mvn -B test --file pom.xml

  automerge:
    runs-on: ubuntu-latest
    needs: run_tests
    if: success() && github.event_name == 'pull_request'  # Ensure the automerge step only runs for PR events

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: automerge
      uses: "pascalgn/automerge-action@v0.16.3"
      env:
        GITHUB_TOKEN: "${{ secrets.PAT }}"
        MERGE_LABELS: "automerge"
        MERGE_METHOD: "squash"
        MERGE_COMMIT_MESSAGE: "automatic"
        MERGE_FORKS: "true"
        MERGE_RETRIES: "50"
        MERGE_RETRY_SLEEP: "10000"
        MERGE_REQUIRED_APPROVALS: "1"
        UPDATE_METHOD: "rebase"

permissions:
  pull-requests: write
