permissions: write-all
name: Automerge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. 触发 tests 工作流
      - name: Trigger tests workflow via GitHub API
        uses: actions/github-script@v5
        with:
          script: |
            const response = await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'prop.yml',  // 你的 tests 工作流的文件名
              ref: context.sha  // 当前 commit hash
            });
            console.log('Triggered workflow response: ', response);

      # 3. 等待自动化测试结果
      - name: Wait for tests to complete
        run: |
          echo "Waiting for tests to finish..."
          sleep 60  # 等待60秒，确保测试完成

      # 4. 自动添加 'automerge' 标签（如果尚未添加）
      - name: Add automerge label if not present
        uses: actions/github-script@v5
        with:
          script: |
            const pr = context.payload.pull_request;
            const labels = pr.labels.map(label => label.name);
            if (!labels.includes("automerge")) {
              await github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: ["automerge"]
              });
            }

      # 5. 自动合并
      - name: Automerge PR
        uses: "pascalgn/automerge-action@629929da409181990e4e638dcf84a74e11d3af66"
        env:
          GITHUB_TOKEN: "${{ secrets.abcd }}"  # 使用自定义的PAT或GitHub的默认token
          MERGE_LABELS: "automerge,!work in progress"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
